defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: basic

hydra:
  mode: MULTIRUN #RunMode.RUN
  # output_subdir: null
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: "vision"
    storage: null
    n_trials: 3
    n_jobs: 1
    params:
      train.epochs: choice(1,2)
      train.lr: choice(0.0002, 3e-4)

train:
  epochs: 3
  lr: 3e-4
  weight_decay: 5e-5

save_model_path: model_weights/model_weights.pt
in_channels: 3
num_classes : 102

dataset:
  root: ../data # for GCP - use "data/""
  dataset: Flowers102 # Flowers102 or FashionMNIST

show_model_summary: False

